plugins {
	id 'java'
}

repositories {
	mavenLocal()
	maven {
		url = 'https://repo.runelite.net'
		content { includeGroupByRegex("net\\.runelite.*") }
	}
	mavenCentral()
}

def runeLiteVersion = 'latest.release'

dependencies {
	compileOnly group: 'net.runelite', name: 'client', version: runeLiteVersion

	testImplementation 'junit:junit:4.12'
	testImplementation group: 'net.runelite', name: 'client', version: runeLiteVersion
	testImplementation group: 'net.runelite', name: 'jshell', version: runeLiteVersion
}

group = 'com.setuppicker'
version = '1.3.0'

tasks.withType(JavaCompile) {
	options.encoding = 'UTF-8'
	options.release.set(11)
}

tasks.register('runClient', JavaExec) {
	group = 'application'
	description = 'Runs RuneLite in developer mode with this plugin loaded'
	classpath = sourceSets.test.runtimeClasspath
	mainClass = 'com.setuppicker.SetupPickerPluginTest'
	jvmArgs '-ea'
	args '--developer-mode', '--debug'
}
